"use client";
import { useEffect, useMemo, useState } from "react";
import { trackEvent } from "@/lib/analytics";
export default function ToolsPage() {
  const [income, setIncome] = useState(4500); const [essential, setEssential] = useState(2200); const [other, setOther] = useState(700);
  const available = useMemo(() => income - essential - other, [income, essential, other]);
  useEffect(() => { trackEvent("tool_view", { tool: "capacidad_mensual_simple" }); }, []);
  return <div className="mx-auto max-w-4xl px-4 py-14 sm:px-6"><div className="max-w-2xl"><p className="text-sm font-semibold text-[var(--brand)]">HERRAMIENTAS</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">Una calculadora simple antes de herramientas más avanzadas.</h1><p className="mt-4 text-lg leading-8 text-slate-600">Esta primera herramienta solo estima cuánto queda después de los gastos registrados. No recomienda productos ni sustituye un presupuesto real.</p></div><div className="mt-10 rounded-[2rem] border border-slate-200 bg-white p-5 sm:p-8"><div className="grid gap-4 sm:grid-cols-3">{[["Ingreso neto", income, setIncome],["Gastos esenciales", essential, setEssential],["Otros gastos", other, setOther]].map(([label, value, setter]) => <label key={String(label)} className="text-sm font-medium">{String(label)}<input type="number" min="0" step="10" value={Number(value)} onChange={(e) => (setter as (n:number)=>void)(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-3" /></label>)}</div><div className="mt-6 rounded-3xl bg-[var(--brand-soft)] p-5"><p className="text-sm text-slate-600">Disponible antes de deudas y ahorro</p><p className={`mt-1 text-3xl font-semibold ${available < 0 ? "text-red-700" : "text-slate-950"}`}>{new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(available)}</p><p className="mt-2 text-sm leading-6 text-slate-600">Es una referencia. Si el resultado es negativo, el primer problema a revisar es la relación entre ingresos y gastos antes de asumir nuevos pagos.</p></div></div></div>;
}
